server:
  port: 8002

eureka:
  instance:
    instance-id: eurika-002 #此实例注册到eureka服务端的唯一的实例ID
    hostname: eurika002
  server:
    enable-self-preservation: true  #false关闭自我保护机制
    eviction-interval-timer-in-ms: 60000 #设置无效服务清理间隔（单位：毫秒 默认是60*1000）
  client:
    registerWithEureka: true #false不把自己作为一个客户端注册到自己身上
    serviceUrl:
      defaultZone: http://eurika001:8001/eureka/ #服务注册地址

spring:
  application:
    name: eurika #项目名，此实例注册到eureka服务端的name